In [1]:
# Artificial Neural Network

In [2]:
# Part 1 - Data Preprocessing

In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
import matplotlib.pyplot as plt

In [4]:
dataset = pd.read_csv('C:\\Users\\peech\\OneDrive\\Documents\\Churn_Modelling.csv')

In [5]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [7]:
len(dataset)

10000

In [8]:
X = dataset.iloc[:, 3:13].values

In [9]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y = dataset.iloc[:,-1].values

In [11]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [12]:
# Encoding categorical data
# Encoding independent variable

In [12]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [13]:
labelencoder_x_1 = LabelEncoder()

In [14]:
X[:,1] = labelencoder_x_1.fit_transform(X[:,1])

In [15]:
X

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [16]:
labelencoder_x_2 = LabelEncoder()

In [17]:
X[:,2] = labelencoder_x_2.fit_transform(X[:,2])

In [18]:
X

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [19]:
onehotencoder = OneHotEncoder(categorical_features=[1])

In [20]:
X = onehotencoder.fit_transform(X).toarray()

In [21]:
X

array([[1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 0.0000000e+00, 1.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [22]:
X[:,3]

array([619., 608., 502., ..., 709., 772., 792.])

In [23]:
X[:,4]

array([0., 0., 0., ..., 0., 1., 0.])

In [24]:
X = X[:, 1:]

In [25]:
X

array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

In [26]:
X.shape

(10000, 11)

In [27]:
# Splitting dataset into training set and test set

In [28]:
from sklearn.model_selection import train_test_split

In [29]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [30]:
# Feature Scaling

In [30]:
from sklearn.preprocessing import StandardScaler

In [31]:
sc = StandardScaler()

In [32]:
X_train = sc.fit_transform(X_train)

In [33]:
X_test = sc.transform(X_test)

In [34]:
print(X_train)

[[-0.5698444   1.74309049  0.16958176 ...  0.64259497 -1.03227043
   1.10643166]
 [ 1.75486502 -0.57369368 -2.30455945 ...  0.64259497  0.9687384
  -0.74866447]
 [-0.5698444  -0.57369368 -1.19119591 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [-0.5698444  -0.57369368  0.9015152  ...  0.64259497 -1.03227043
   1.41231994]
 [-0.5698444   1.74309049 -0.62420521 ...  0.64259497  0.9687384
   0.84432121]
 [ 1.75486502 -0.57369368 -0.28401079 ...  0.64259497 -1.03227043
   0.32472465]]


In [35]:
print(X_test)

[[ 1.75486502 -0.57369368 -0.55204276 ...  0.64259497  0.9687384
   1.61085707]
 [-0.5698444  -0.57369368 -1.31490297 ...  0.64259497 -1.03227043
   0.49587037]
 [-0.5698444   1.74309049  0.57162971 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-0.5698444   1.74309049 -0.74791227 ...  0.64259497 -1.03227043
   0.71888467]
 [ 1.75486502 -0.57369368 -0.00566991 ...  0.64259497  0.9687384
  -1.54507805]
 [ 1.75486502 -0.57369368 -0.79945688 ...  0.64259497 -1.03227043
   1.61255917]]


In [38]:
# Part 2 - Making the ANN

In [39]:
# Importing the Keras libraries and packages

In [37]:
import keras

In [38]:
from keras.models import Sequential # What will be used to initialize the Neural Network

In [39]:
from keras.layers import Dense # For Creating the layers in the Artificial Neural Network

In [43]:
# Initializing the ANN - Defining it as a sequence of layers

In [45]:
# Two ways of Initializing a Deep Learning Model: It's either by defining this sequence of layers or the other way of defining a graph

In [46]:
# Here we will initialize our deep learning model by defining it as a sequence of layers

In [40]:
classifier = Sequential() # Don't need to pass in any arguments because we define the layers later step-by-step
# Initialized the ANN

In [42]:
# Adding the input layer and the first hidden layer

In [42]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11)) 
# activation = 'relu' here because this is the hidden layer and activation for hidden layer is rectifier function
# add method is used to add the different layers in Neural Network
# Number of nodes in input layer = 11 because number of independent variables = 11
# Number of nodes in output layer = 1
# Average = (11+1)/2 = (12)/2 = 6 Nodes in hidden layer; output_dim/units
# input_dim = 11 to represent number of independent variables = 11; Need to specify this for first hidden layer because no input layer was created yet

In [44]:
# Adding the second hidden layer

In [43]:
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [46]:
# Adding the output layer

In [45]:
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation= 'sigmoid'))

In [54]:
# Compiling the ANN

In [46]:
classifier.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy']) 
# loss is like sum of squared errors in linear regression
# loss function is logarithmic loss

In [56]:
# Fitting ANN to the training set

In [47]:
classifier.fit(X_train, y_train, batch_size=10, epochs = 100)
# batch_size is number of observations after which you want to update the weights
# epoch is around when whole training set passed through ANN

Epoch 1/100
8000/8000 [==============================] - 2s 231us/step - loss: 0.4849 - acc: 0.7952
Epoch 2/100
8000/8000 [==============================] - 1s 114us/step - loss: 0.4289 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4228 - acc: 0.7962
Epoch 4/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4187 - acc: 0.8226
Epoch 5/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4164 - acc: 0.8255
Epoch 6/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4145 - acc: 0.8276
Epoch 7/100
8000/8000 [==============================] - 1s 163us/step - loss: 0.4131 - acc: 0.8305
Epoch 8/100
8000/8000 [==============================] - 1s 139us/step - loss: 0.4115 - acc: 0.8315
Epoch 9/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4103 - acc: 0.8305
Epoch 10/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4098 - acc: 0.8314

8000/8000 [==============================] - 2s 191us/step - loss: 0.4006 - acc: 0.8362
Epoch 83/100
8000/8000 [==============================] - 1s 143us/step - loss: 0.4004 - acc: 0.8352
Epoch 84/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4003 - acc: 0.8347
Epoch 85/100
8000/8000 [==============================] - 1s 98us/step - loss: 0.4006 - acc: 0.8356
Epoch 86/100
8000/8000 [==============================] - 1s 110us/step - loss: 0.4000 - acc: 0.8354
Epoch 87/100
8000/8000 [==============================] - 1s 122us/step - loss: 0.4004 - acc: 0.8359
Epoch 88/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.4006 - acc: 0.8350
Epoch 89/100
8000/8000 [==============================] - 2s 189us/step - loss: 0.4001 - acc: 0.8339
Epoch 90/100
8000/8000 [==============================] - 1s 118us/step - loss: 0.4002 - acc: 0.8367
Epoch 91/100
8000/8000 [==============================] - 1s 132us/step - loss: 0.4001 - acc: 0.8351
Epoc

In [58]:
# Making the predictions and evaluating the model

In [48]:
y_pred = classifier.predict(X_test)

In [49]:
print(y_pred)

[[0.29824588]
 [0.3537032 ]
 [0.13537176]
 ...
 [0.14392255]
 [0.15592273]
 [0.10366207]]


In [50]:
y_pred[5]

array([0.83303785], dtype=float32)

In [62]:
# Making the Confusion Matrix

In [63]:
# threshold is 0.5

In [51]:
def createBinaryPredictionsLst(val):
    if val < 0.5:
        return 0
    else:
        return 1
binary_predictions_lst = [createBinaryPredictionsLst(value) for value in y_pred]

In [52]:
binary_predictions_lst

[0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,


In [53]:
y_pred = (y_pred > 0.5)

In [54]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
from sklearn.metrics import classification_report

In [57]:
print(confusion_matrix(y_true = y_test, y_pred = binary_predictions_lst))

[[1539   56]
 [ 261  144]]


In [58]:
print(confusion_matrix(y_true = y_test, y_pred = y_pred))

[[1539   56]
 [ 261  144]]


In [59]:
print(classification_report(y_true = y_test, y_pred = binary_predictions_lst))

             precision    recall  f1-score   support

          0       0.85      0.96      0.91      1595
          1       0.72      0.36      0.48       405

avg / total       0.83      0.84      0.82      2000



In [60]:
print(classification_report(y_true = y_test, y_pred = y_pred))

             precision    recall  f1-score   support

          0       0.85      0.96      0.91      1595
          1       0.72      0.36      0.48       405

avg / total       0.83      0.84      0.82      2000



In [61]:
print((1539+144)/2000 * 100)

84.15
